//HintName: Tests.GodotComponent.g.cs

/*
 * GodotComponent.g.cs
 *
 * NOTE: This file is automatically generated. Any changes made to this file will be lost.
 */

namespace Tests;

using Godot;

public partial class GodotComponent
{
    private void ValidateExports()
    {
        if (_rayCast == null)
        {
            GD.PushError("Null Export: GodotComponent _rayCast RayCast3D");
        }
        if (_node == null)
        {
            GD.PushError("Null Export: GodotComponent _node Node3D");
        }
    }
}