//HintName: Tests.GodotComponent.g.cs

/*
 * GodotComponent.g.cs
 *
 * NOTE: This file is automatically generated. Any changes made to this file will be lost.
 */

namespace Tests;

using Godot;

public partial class GodotComponent
{
    private void ValidateExports()
    {
        if (_customComponent == null)
        {
            GD.PushError("Null Export: GodotComponent _customComponent CustomComponent");
        }
    }
}