using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GodotExportValidator;

[Generator]
public class ExportValidatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var syntaxProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            typeof(ExportValidation).FullName!,
            IsSyntaxTarget,
            GetSyntaxTarget
        );
        
        context.RegisterSourceOutput(syntaxProvider.Collect(), OnExecute);
    }

    private bool IsSyntaxTarget(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        return syntaxNode is ClassDeclarationSyntax;
    }

    private ClassExportValidation GetSyntaxTarget(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        var classSymbol = (ITypeSymbol)context.TargetSymbol;
        var nullCheckList = new List<ExportToNullValidate>();

        foreach (var memberSymbol in classSymbol.GetMembers())
        {
            if (memberSymbol is not IFieldSymbol fieldSymbol)
            {
                // We only validate fields
                continue;
            }
            
            foreach (var attribute in memberSymbol.GetAttributes())
            {
                cancellationToken.ThrowIfCancellationRequested();

                if (attribute.AttributeClass!.Name == nameof(ExportNullCheck))
                {
                    nullCheckList.Add(new ExportToNullValidate(
                        fieldSymbol.Name,
                        fieldSymbol.Type.Name));
                }
            }
        }

        return new ClassExportValidation(
            GeneratorHelpers.GetNamespace(context.TargetNode as ClassDeclarationSyntax),
            classSymbol.Name,
            nullCheckList.ToImmutableList());
    }

    private static void OnExecute(SourceProductionContext context, ImmutableArray<ClassExportValidation> classValidations)
    {
        foreach (var classValidation in classValidations)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            var result = GenerateValidationClass(classValidation);
            context.AddSource($"{classValidation.Namespace}.{classValidation.ClassName}.g.cs", SourceText.From(result, Encoding.UTF8));
        }
    }
    
    private static string GenerateValidationClass(ClassExportValidation classValidation)
    {
        var sb = new StringBuilder();
        sb.Append($@"
/*
 * {classValidation.ClassName}.g.cs
 *
 * NOTE: This file is automatically generated. Any changes made to this file will be lost.
 */

namespace {classValidation.Namespace};

using Godot;

public partial class {classValidation.ClassName}
{{
    private void ValidateExports()
    {{");

        foreach (var field in classValidation.ValidationList)
        {
            sb.Append($@"
        if ({field.FieldName} == null)
        {{
            GD.PushError(""Export null: {classValidation.ClassName} {field.FieldName} {field.FieldType}"");
        }}");
        }
        
        sb.Append($@"
    }}
}}");

        return sb.ToString();
    }

    private record struct ClassExportValidation(
        string Namespace,
        string ClassName,
        IImmutableList<ExportToNullValidate> ValidationList
    );

    private record struct ExportToNullValidate(string FieldName, string FieldType);
}
